# Autograd with tensors

In [0]:
import torch

In [0]:
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[ 0.5401, -0.3513, -2.8749],
        [-0.6433, -0.1751,  1.1154],
        [-1.5005,  0.8947,  0.8887],
        [-0.8462,  0.3629, -0.5127]], requires_grad=True)

In [4]:
w.requires_grad_(False)

tensor([[ 0.5401, -0.3513, -2.8749],
        [-0.6433, -0.1751,  1.1154],
        [-1.5005,  0.8947,  0.8887],
        [-0.8462,  0.3629, -0.5127]])

In [5]:
w.requires_grad_(True)

tensor([[ 0.5401, -0.3513, -2.8749],
        [-0.6433, -0.1751,  1.1154],
        [-1.5005,  0.8947,  0.8887],
        [-0.8462,  0.3629, -0.5127]], requires_grad=True)

In [6]:
y = torch.exp(w)
print(y)

tensor([[1.7161, 0.7037, 0.0564],
        [0.5256, 0.8393, 3.0507],
        [0.2230, 2.4467, 2.4319],
        [0.4290, 1.4375, 0.5989]], grad_fn=<ExpBackward>)


In [7]:
print(y.grad_fn)

In [8]:
outp = y.mean()
print(outp)

tensor(1.2049, grad_fn=<MeanBackward0>)


In [9]:
# gradients are none
print(w.grad)

None


In [0]:
# gradients are calculated when you run the back calculation

In [0]:
outp.backward()

In [11]:
# after backpropagation gradients have been calculated
print(w.grad)

tensor([[0.1430, 0.0586, 0.0047],
        [0.0438, 0.0699, 0.2542],
        [0.0186, 0.2039, 0.2027],
        [0.0358, 0.1198, 0.0499]])


In [12]:
print(w.detach())

tensor([[ 0.5401, -0.3513, -2.8749],
        [-0.6433, -0.1751,  1.1154],
        [-1.5005,  0.8947,  0.8887],
        [-0.8462,  0.3629, -0.5127]])


In [13]:
print(outp.requires_grad)

True


In [16]:
with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad)

False
