# Tensors 

In [0]:
import torch

## zeros()

In [2]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [3]:
w.size()

torch.Size([4, 3])

In [4]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [5]:
w = torch.randn(4,3)
w

tensor([[-0.3271, -0.0798,  0.9150],
        [ 0.1484,  0.1867,  0.5760],
        [-0.6231, -0.1830,  0.8625],
        [ 1.0599,  0.2004,  0.9854]])

In [7]:
t = torch.randn_like(w)
t

tensor([[-1.1226,  0.0118, -0.6826],
        [ 0.8342,  0.0090, -0.0343],
        [ 0.5738, -0.4362,  0.7782],
        [-1.6400, -1.5080, -0.5383]])

## fill_()

In [8]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [9]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [11]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [12]:
type(w.numpy())

numpy.ndarray